### ISSUE TITLE
New state variables reset when changed within the state

### ISSUE THREAD

**Issue by johnarban** [cosmicds/hubbleds#182]
Whenever I create a new state variable in a stage, it seems to just automatically and sometimes _silently_ reset itself. If the variable is changed from a new cell in the notebook, that change stays. This seems to only affect new variables since March, but I really don't have any idea what causes it.

**Comment by johnarban** [comment]
This can be checked on this commit johnarban/hubbleds@b6929b6edd01fc295b41343c14291942062e3d43

**Comment by johnarban** [comment]
this solution seems to have spotty and inconsistent success. after switching to using int's these aren't behaving any better.

**Comment by patudom** [comment]
I think we have hacky workarounds for all the lingering issues we've been seeing, so downgrading this from "critical" to "for later."

**Comment by patudom** [comment]
Don't think this has been an issue in solara.
