### ISSUE TITLE
When the screen has a certain size sometimes buttons can't be clicked

### ISSUE THREAD

**Issue by johnarban** [cosmicds/hubbleds#189]
This is a long-standing issue. a good example is the stage 1 guideline where we enter the wavelength values.

**Comment by patudom** [comment]
This is actually only an issue in the notebook. When a guideline is taller than the viewer in its row, the div of the next row down invisibly covers the buttons. We set a z-index for the buttons so they work fine in voila, but the notebook ignores the z index for some reason. It's annoying for development, but the only way we've found around it is to resize the window so the guideline buttons are clear of the next row.
