### ISSUE TITLE
recursion error on bqplot:xzoom

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#200]
@johnarban, I think this is an issue we can ignore for the pilot, right? Noting this here, so we don't lose track of it.

              I switched to using the `hubble:wavezoom` tool which deactivates the zoom tool after a selection. 

Currently the `BqplotZoom`-based `bqplot:xzoom` tool reactivates itself after making a selection 
https://github.com/cosmicds/cosmicds/blob/ad8f5bba580d378dda83a4744a619f06721a208d/cosmicds/tools/zoom_tools.py#L32

If someone wants the tool to deactivate, say trying to use `extend_tool`, it results in a `RecursionError`. For example using the following function
```python
def extend_function(viewer, tool):
    # either 1 or both lines will create the error
    viewer.toolbar.tools[tool].deactivate()
    viewer.toolbar.active_tool = []
extend_tool(viewer, tool, partial(extend_function, viewer, tool), activate_before_tool = False)
```
Removing line 32 doesn't seem to fix the issue (_in fact_, it remains active even with that line removed)

`hubble:wavezoom` solves this by defining it's own `update_selection` function which deactivates the tool by doing
```python
def update_selection(self):
    ...
    super().update_selection()
   ...
   self.deactivate()
```
https://github.com/cosmicds/hubbleds/blob/9ca387ca79be97bcfda67427725efd7a318f1964/src/hubbleds/tools/wavelength_zoom.py#L31C9

_Originally posted by @johnarban in https://github.com/cosmicds/hubbleds/issues/199#issuecomment-1529239576_

**Comment by johnarban** [comment]
Yeah, it's fine to just use hubble:wavezoom. this issue doesn't affect us anywhere else

**Comment by Carifio24** [comment]
This is really just an incompatibility between how we want this tool to work and how our zoom tools work. The generic zoom tools want to stay active until they're explicitly deactivated. I set them up like this to match the behavior of other glue zoom functionality.

Ultimately the general zoom tools should behave whichever way we think we'll most commonly want. For a tool that wants different behavior (like this one), I think overriding superclass methods is a fine approach.
