### ISSUE TITLE
Dot plot slideshow viewer marker sizes not set correctly on first slide

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#201]
cosmetic:

The first slide of the slideshow still has small dots compared with the other 3 slides. I don't understand why it's doing this, since it's actually the same viewer on all 4 slides. I wondered if maybe there is something about turning on the vertical measuring tool in Slide 2 that makes the dot markers update, but I can't imagine why.

<img width="581" alt="Screen Shot 2023-04-30 at 3 01 40 PM" src="https://user-images.githubusercontent.com/12750048/235374267-4981f962-4b01-4730-984c-224617a35c9a.png">
<img width="579" alt="Screen Shot 2023-04-30 at 3 01 49 PM" src="https://user-images.githubusercontent.com/12750048/235374274-9a13ed4d-68f4-4129-bb93-7dab2353b899.png">

_Originally posted by @patudom in https://github.com/cosmicds/hubbleds/issues/199#issuecomment-1529129538_

**Comment by johnarban** [comment]
@nmearl pointed out that the tutorial is displayed twice. We should only have one visible

**Comment by johnarban** [comment]
close in #210
