### ISSUE TITLE
Add unit label to measuring line and make line taller

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#222]
This can definitely wait for after the stress testing (and after the pilot too if it would be more than ~10-15 minutes' work.)
<img width="614" alt="Screen Shot 2023-05-04 at 12 41 15 PM" src="https://user-images.githubusercontent.com/12750048/236270148-293119f9-47b9-4e35-8272-041903818bd2.png">

**Comment by johnarban** [comment]
the height is controlled by a parameter that is pretty easy to change. How tall do you want it?

**Comment by patudom** [comment]
I think tall enough to go above the tallest bin. It looks weird to me that it only makes it up partway.

**Comment by Carifio24** [comment]
If it's helpful, the default `y_max` for the histogram viewer state will be [1.2 times the highest histogram bar](https://github.com/Carifio24/glue/blob/master/glue/viewers/histogram/layer_artist.py#L119) - that is, the highest bar will be 5/6 as tall as the viewer figure. Using that together with the viewer height should give us a good estimate of how tall the line should be.
