### ISSUE TITLE
Stage 4 - student_sli layer needs to be hidden from layer_viewer

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#228]
This showed up in stress testing on the server on Wednesday, but no one recalls seeing it during testing on Thursday. We are not sure what could have changed, but we should keep an eye out for this and remove it if it comes back.

**Comment by johnarban** [comment]
So I am seeing it in my testing, after restaring a user. 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/7862929/236537128-2dbbed64-8355-48ed-8289-9b9e26358dd1.png">
