### ISSUE TITLE
Stage 5 ALL CLASSES histogram viewer at age_dis1c needs limits reset call

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#235]
Why does it think there is an age of 125 Gyr anyway?

<img width="590" alt="Screen Shot 2023-05-06 at 3 46 20 PM" src="https://user-images.githubusercontent.com/12750048/236643845-39149d35-ff68-41ec-adc6-779915977c30.png">

**Comment by patudom** [comment]
There is weird limit resetting behavior in the paired student vs class age histograms too.

If you reset limits in ALL STUDENTS, you get this:
<img width="558" alt="Screen Shot 2023-05-06 at 3 49 48 PM" src="https://user-images.githubusercontent.com/12750048/236643941-0c479605-3323-446e-b6c7-16982de65a56.png">

If you reset limits in ALL CLASSES, you get this:
<img width="562" alt="Screen Shot 2023-05-06 at 3 49 35 PM" src="https://user-images.githubusercontent.com/12750048/236643956-caab785a-a779-40d2-b397-550b92695c71.png">

**Comment by johnarban** [comment]
I'll take a look.
