### ISSUE TITLE
Show which stage student is in

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#247]
I think we inadvertently disabled functionality that tells you what stage you're on. Now, we tell them if a stage is complete, but if you backtrack to earlier stages, there isn't an obvious way to know which stage you are currently on.

In this screenshot, I am on Stage 4.
<img width="794" alt="Screen Shot 2023-05-07 at 10 56 51 PM" src="https://user-images.githubusercontent.com/12750048/236724115-a489ebdc-1efe-4e4e-a073-5b3beacc3e23.png">

**Comment by Carifio24** [comment]
@patudom What about something like this? The highlight color could be anything in our theme.
![show_stage](https://github.com/cosmicds/hubbleds/assets/14281631/5c144e5a-bdc3-4770-94c5-ec19c999d26b)

**Comment by Carifio24** [comment]
Also, there technically is a small visual cue in the current display - there's a thin vertical bar (and an expanded gap) in the menu between the current and next stages, though it's something that a lot of students might miss.
