### ISSUE TITLE
Histogram bins between glue and numpy don't match

### ISSUE THREAD

**Issue by johnarban** [cosmicds/hubbleds#260]
This is a relatively minor issue but, there seems to be an issue in deriving bin values in glue (at least in a way that is consistent with `numpy`)

If I am on student 3887 and run

```python

xmin, xmax, hist_n_bin = (6.5, 23.5, 17)
data = app.data_collection['all_class_summaries']
x_att = 'Age (Gyr)'
hist_glue = data.compute_histogram([data.id[x_att]],range=[(xmin,xmax)], bins=[hist_n_bin], log=[False])
# hist: array([1., 0., 0., 1., 0., 2., 4., 6., 3., 3., 0., 0., 0., 0., 0., 0., 1.])

hist_np = np.histogram(data[x_att], range = (xmin,xmax), bins = hist_n_bin)
# hist: array([1, 0, 0, 0, 1, 2, 3, 7, 3, 3, 0, 0, 0, 0, 0, 0, 1]),

# bins: array([ 6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5]))
# when I get the bins from glue via viewer.state.bins, the bins are the same

# The actual data going in is: array([ 7.4, 10.5, 12. , 12.3, 13.2, 13.2, 13.4, 13.5, 13.8, 13.8, 14. , 14.2, 14.2, 14.4, 14.6, 15.2, 15.4, 15.6, 15.8, 16. , 23.4])
```

I noticed this because the id slider shows 7 ticks for 14, but the histogram only shows 6 values. The value `13.5` should be in the bin for `[13.5, 14.5)` but glue seems to place it one bin lower, similarly with 10.5. From what I can tell, [compute_histogram](https://github.com/glue-viz/glue/blob/c0eb36c9e56a53d2ebef44068d58934ab04a0d1c/glue/core/data.py#L521) uses `fast_histogram`, but running `fast_histogram` directly that returns the same value as `np.histogram`. 

<img width="645" alt="image" src="https://github.com/cosmicds/hubbleds/assets/7862929/68878e27-f276-4bd1-b8d0-b33b6d81c667">

https://github.com/cosmicds/hubbleds/assets/7862929/99b8f1f4-8488-4d42-92ac-5311fc9d60b9

**Comment by Carifio24** [comment]
I'm wondering if [this](https://github.com/glue-viz/glue/blob/c0eb36c9e56a53d2ebef44068d58934ab04a0d1c/glue/core/data.py#L2014) could be the cause. If the range is getting slightly widened, this would move things right on the bin edges (like e.g. 10.5, 13.5 in the above) down into the bin below.

**Comment by johnarban** [comment]
Yeah, I was thinking along similar lines. I'm not sure how to work around that though. I only noticed this when working on #259 (which manually sets bins to be 1 Gyr wide ever with edges ate 0.5...) which was something @patudom I were discussing

**Comment by patudom** [comment]
Per Jon's comment above, np.spacing adds a tiny bit of padding to the values in the histogram, which means that something that was 13.5 and would be in the 13 bin, but if you have 1.35 + tiny spacing delta, it moves up to the next bin.

Solution is to store more than 1 decimal place in the age values in the db table. We have gone with 3 decimal places for now.
