### ISSUE TITLE
Improve how we demonstrate the relationship between more data and reduced uncertainty

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#276]
One potential point of confusion that came up in the May Pilot is that our pairing of the All Classes and All Students histograms muddles the relationship between an increase in the number of data points and a decrease in uncertainty.

We want students to see that the All Students histogram has a wider range of age values than the All Classes histogram because each class measurement is made with ~20x more galaxies than each student measurement.

However, the number of galaxies that goes into a particular age measurement is invisible to the user who is only looking at the histograms. Also, the All Students histogram displays a far larger number of data points than the All Classes histogram.

I think we can reduce this confusion by offering a button on the All Students histogram to randomly select N values to display (where N is the same number of age values being shown in the All Classes histogram).

I'm not sure if there is a way to make the number of galaxies involved in each age measurement more tangible to students looking at the histograms, but I think the random matched N displayed in the histograms might be a good start.

@johnarban and @heywooddogwood, does that seem like that would be helpful, or would it just add more confusion?

**Comment by johnarban** [comment]
Well, randomly subsetting to have the same N will make it 🍎 : 🍎 , but I think it would be confusing. 

I think we just need to carry the explanation of where the class age comes from through. basically reinforcing by repetition.

perhaps in `age_dis1c` we remind students
>Here is a histogram of the class by class age measurements. *Each measurement represented here is the best fit to an entire class's set of galaxy measurements. It's a large number of student measurements (and thus galaxies) aggregated into a single value* 

Like, what we want them to see is that each class count is an average over many students,  I think. That is what we would want them to put in the `lac_bia3` box.

**Comment by johnarban** [comment]
so `you_age1c` sort of moves on without making an point about this exercise. It was obvious why I fit a line to my data (to get an age). This kinda moves by without relating back to the histogram. 
<img width="1072" alt="image" src="https://github.com/cosmicds/hubbleds/assets/7862929/8101756f-32c1-4663-8b93-3851a42e6f21">

Perhaps the previous guideline (really `tre_lin2c`) can say something like 
>"Now that you've drawn what conclusions you can from looking at individual students' **age** measurements , let's turn back to your whole class's dataset. We can treat the entire class's set of galaxy measurements, graphed here, the same way we treated your measurements and derive a single age using you and your classmates measurements
>
>Click....."

I feel like maybe it could more directly compare the two methods.
