### ISSUE TITLE
Fix layout issues on some screen sizes

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#317]
Consider changing overall stage_x.vue layout to use the multiple columns in xl mode (instead of lg), and/or close left menu for larger screens than currently specified to avoid this type of situation:

<img width="990" alt="Screen Shot 2023-10-25 at 6 29 01 PM" src="https://github.com/cosmicds/hubbleds/assets/12750048/6b489c0a-8b68-4abe-ba2b-b4a6af399121">

**Comment by johnarban** [comment]
This seems to be a notebook specific issue. When we go to small screens the layout changes so that the text box isn't squished.
