### ISSUE TITLE
Check pro_dat6 mc question

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#327]
One additional item relating to #300, @johnarban, I think we should leave this alone for next week's implementation, but Harry and I think the responses we are currently calling "neutral" should be downgraded to "wrong" if we are sure the logic throughout is correct. Every instance I've seen has looked correct, but I think every class I've looked at has had a higher age than HSTKP, so I haven't really tested this thoroughly in the opposite direction, or when it's too close to call.

**Comment by johnarban** [comment]
I agree it should be downgraded to wrong. the logic should be correct, but it is hard to test. i might be able to manually test it by setting the class age manually in the notebook
