### ISSUE TITLE
Track down issue where high/low age values student saw for slider did not agree with what was in the state

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#339]
This happened on 11/29/2023 to real student 4372 and teacher experimenting as student 4389.

**Comment by Carifio24** [comment]
I'm not sure yet what the issue was with these. The high and low class ages are directly set based on the slider's values [here](https://github.com/cosmicds/hubbleds/blob/main/src/hubbleds/stages/stage_5.py#L350), and nowhere else, so it's difficult to see how they could get out of sync.
