### ISSUE TITLE
Issues from run through of Nick's new Solara branch as student_id=0

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#342]
@nmearl, I am deeply impressed by how well the updated pywwt + solara version is working!!

I ran through as `student_id = 0`, so there will likely be other issues that surface when state testing as an actual student in a class, but here are the initial issues I ran into:

### WWT issues (most we already knew about):

- [x] Galaxy markers need to be green and scale with screen not world

These are now in #346:  
- [x] ~~WWT background needs to be SDSS~~
- [x] ~~WWT chrome needs to go away~~

### Other

- [ ] Piggy bank points flash the correct value in upper right corner but then becomes 0
- [x] Theme colors are not being applied correctly
- [ ] Input text seems to only selectively register. For example, text I entered for shortcomings 1 & 2 did not carry over to the uncertainty slideshow, but "Other shortcomings" did (see screenshot). If I backtrack to the marker with the inputs, the first 2 are missing. The same thing happened with my age estimate/confidence interval entries. 2 of the 3 values I entered were stored, but 1 was not. I don't know if this would behave differently if I were writing my state to the db (which I am not as student 0).
- [ ] Guideline pro_dat6 - displays hubble data, but it should be showing HST data.
- [ ] If I backtrack through guidelines, the displayed MC response that the question is "frozen" on is not my final choice - I'm guessing it was my first choice. (see screenshot)
- [ ] When advancing to Stage 5, it flashes to Stage 5, then backs up to end of Stage 4. It will advance properly if I try a second time.

<img width="1004" alt="Screenshot 2024-01-11 at 10 33 14 AM" src="https://github.com/cosmicds/hubbleds/assets/12750048/7cde3ba5-0f18-4e71-957c-464dab4a3304">

<img width="379" alt="Screenshot 2024-01-11 at 10 47 43 AM" src="https://github.com/cosmicds/hubbleds/assets/12750048/f8edc5ae-efd5-4096-896a-2bec472c1858">

**Comment by johnarban** [comment]
On the newest version of the app - the last 3 issues do not seem to be happening. This was done as a regular student (the new auth system has been implemented, so we don't log in as student 0

 ❓  Guideline pro_dat6 - displays hubble data, but it should be showing HST data.
 ❓ If I backtrack through guidelines, the displayed MC response that the question is "frozen" on is not my final choice - I'm guessing it was my first choice. (see screenshot)
 ❓ When advancing to Stage 5, it flashes to Stage 5, then backs up to end of Stage 4. It will advance properly if I try a second time.
