### ISSUE TITLE
Make valid entries into free response boxes trigger gates to "open"

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#453]
Typing in the FR box with valid content does not automatically change the "before-next" content to become the "next" button like it used to. You have to explicitly do something to leave the box before the next button will appear, and that is not intuitive behavior. I could picture a student pressing "enter" after entering their response, but that just adds more lines inside the FR box. I wouldn't expect a student to think to press "tab" or click somewhere outside the box to get the content to register, which is what you have to do now. Is this something we can change?

**Comment by patudom** [comment]
Discussed this with @Carifio24 and @nmearl.

Currently, the trigger for updating the state (and therefore the db) is for the input box to lose focus, which leads to the non-intuitive behavior described above.

We don't want to change the trigger to be "listen for changes to the text" because that will trigger state updates for every keystroke and clog the messaging queue.

Possible solutions:
1. Wait for a short period (0.5 - 1 sec?) that gets reset after each keystroke before sending a state update. We'd need to experiment to see what amount of time feels natural, but depending on what we choose, slow typers would still end up triggering a lot of state updates.
2. Have 2 parts to the state update - when student starts typing, that could trigger the gate to open, then when the box loses focus, the response could then be recorded in the state. If we do this, we would not be able to validate responses for numbers vs. text, but maybe that's an acceptable trade since we ran a lot of the early trials without the response validators anyway.
3. Another less attractive option is to put a "submit" button next to the box, which at least gives the student an obvious action to take when they are finished typing their response.

Right now I'm leaning towards option 2. @johnarban, do you have thoughts or suggestions around this?

**Comment by Carifio24** [comment]
I also think we could incorporate the validators into an option 2-style solution - we could send an update every time the validity changes in addition to the time/focus-based stuff.

**Comment by johnarban** [comment]
So yes to the sending an update on the validity change - that is what I was thinking too, but I don't think we need the timing stuff. So long as the validity gets sent up to the parent and can be handled, it is the only thing that needs to be reactive. We can then use the existing focus-based events to store the final free-response.

**Comment by Carifio24** [comment]
Yeah, I like @johnarban's idea. As long as the validity of the answer matches whether the student can advance, we can make the final update whenever (e.g. on a blur).

**Comment by patudom** [comment]
Done in #517.
