### ISSUE TITLE
Wire up best fit line tool to Stage 4 & 5 viewers

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#477]
- [x] Stage 5 glue viewers - just add glue tool (Jon)
- [x] Stage 4 plotly viewers - need to set up js version of tool (Jon)
- [x] Wire up gates (Pat)

**Comment by Carifio24** [comment]
The first two items should be resolved by #479 and #481.

**Comment by patudom** [comment]
Last item is resolved in #547.
