### ISSUE TITLE
Stage 4 viewers sometimes don't appear on reload

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#492]
I'm not sure if this is a thing that could happen to a student (or if this is only happening to me because I randomly jump around), but I frequently end up with no viewer in Stage 4. Going back to the intro stage, refreshing the page, and then coming back to Stage 4 does not help - sometimes when I've tried, this the title bar for the viewer goes away too. The only way I've found to bring the viewers back is to reset the stage state, which would be problematic if it's possible for this to happen to students going through sequentially.

<img width="1251" alt="Screenshot 2024-07-16 at 4 42 03 PM" src="https://github.com/user-attachments/assets/abfa8212-de8a-4d65-a016-47deb733e888">

**Comment by Carifio24** [comment]
Do you see any errors in the browser console when this happens? Since the graph isn't appearing, my guess would be that there's an issue with loading Plotly.

**Comment by patudom** [comment]
```Uncaught (in promise) ReferenceError: Plotly is not defined
    at VueComponent.mounted (eval at <anonymous> (VueTemplateRenderer.js:351:21), <anonymous>:30:5)
mounted @ VM7451:30Understand this error
```

**Comment by Carifio24** [comment]
So something is causing Plotly to not be loaded, which should happen in the layout via the `PlotlySupport` component (inside of the layout). This component adds a `plotlyPromise` to the window which we then await in the line draw viewer.

Is there any particular sequence of events that causes this to happen?

**Comment by patudom** [comment]
Not that I've noticed. Usually I'm on a guideline where the viewer is visible, but when I refresh the page, the viewer is not there. If I notice any particular patterns going forward, I will note them here.

**Comment by Carifio24** [comment]
Recap for posterity of a dev meeting discussion:

This can be partially resolved by moving the `PlotlySupport` component in the HubbleDS layout outside of the `use_memo` call. Doing this reveals another issue where the entire component won't load. This is due to (at least) one of the `student_plot_data` and `class_plot_data` being an empty array, causing the if condition that displays the component to evaluate false.

**Comment by patudom** [comment]
I haven't seen this issue since the above update was merged, so I am closing this.
