### ISSUE TITLE
from class test: Green dot's don't consistently load

### ISSUE THREAD

**Issue by johnarban** [cosmicds/hubbleds#581]
With large numbers of students logging on, so perhaps to due to slow internet speeds, the green dot's do not consistently load. This I think has two causes
1) WWT is not loading soon enough, and so later commands never get run.
2) If students refresh and come in at too late a marker, the dot's don't get loaded. They are only loaded in one place I think
3) The green dots don't always come back after zooming in.

**Comment by patudom** [comment]
Hopefully we won't see this very often now that Jonathan Fay has helped us fix the WWT server issue.

**Comment by patudom** [comment]
duplicate
