### ISSUE TITLE
Update classes in db

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#610]
This isn't specific to code in this repo, but I'm adding this here so we can keep track of the issue.

@Carifio24, here are the notes I have from our meeting this morning.

For all classes that are contributing an age measurement to the class histogram:

- [x] Filter out any students where we used the "fill galaxies" data set that gives an age of 17 Gyr.
- [x] Filter out students (both real and team) who have wonky measurements that would not pass the velocity & distance guardrail checks.
- [x] Make sure team students are appear uniquely in 1 class. (Can we just kick them out of extra classes they've been added to)
- [x] For team seed or test classes, merge small classes into new classes with 15-20 students.
- [x] For real classes, leave classes with N >= 12 students alone.
- [x] For real classes, merge classes with N < 12 students with a unique seed or test class.

@johnarban and @nmearl - please let us know ASAP if anything in this scheme will mess up test classes you have set up and are currently using.

Please feel free to edit if there is anything I've missed. Thanks!

**Comment by johnarban** [comment]
This should all be fine for me

**Comment by nmearl** [comment]
Sounds good to me.

**Comment by Carifio24** [comment]
Just for posterity, you can find students that don't pass condition 2 (and aren't already being ignore via)

```sql
USE cosmicds_db;
SELECT 
    *
FROM
    HubbleMeasurements
        LEFT OUTER JOIN
    IgnoreStudents ON HubbleMeasurements.student_id = IgnoreStudents.student_id
WHERE
    IgnoreStudents.student_id IS NULL
        AND ABS((rest_wave_value - obs_wave_value) / rest_wave_value) > 0.5
        AND (ang_size_value >= 5
        AND ang_size_value <= 1800); # 1800 arcseconds is 30 arcminutes
```

**Comment by Carifio24** [comment]
For identifying which students are in multiple classes (and how many for each student)

```sql
SELECT student_id, COUNT(*) FROM StudentsClasses
GROUP BY student_id
HAVING COUNT(student_id) > 1;
```

**Comment by Carifio24** [comment]
As for making sure that each student is only in one class, here's a gist with the script that I used to do that:
https://gist.github.com/Carifio24/e9e8a4d683b78ac3288a896a83448971

**Comment by Carifio24** [comment]
To find all of the test classes with < 12 students:
```sql
SELECT 
    id, name, test, COUNT(student_id)
FROM
    Classes
        INNER JOIN
    StudentsClasses ON StudentsClasses.class_id = Classes.id
WHERE
    test = 1
GROUP BY class_id
HAVING COUNT(student_id) < 12;
```

**Comment by Carifio24** [comment]
There's a class named `2023-07 2i2c_beta` with 7 students in it. @patudom do you know whether this is a real class? I can't remember.
