### ISSUE TITLE
Mathjax input boxes don't "remember" inputs

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#616]
- [ ] For example, in Stage 1, at marker `dop_cal4`, if you input the wavelengths into the equation box, open the calculation dialog, then close the dialog, in order to reopen the dialog, you have to re-input the wavelength values.

- [ ] Stage 3: est_dis3 marker always needs angular size input twice before advancing

**Comment by Carifio24** [comment]
So in the Voila version, we used the fact that the app state was frontend-accessible to update the state on (I believe) a focus change.

I think in the Solara version we could achieve the same thing using an event callback that we invoke inside the input listener.
