### ISSUE TITLE
Stage 1 - infinite loop where example wavelength & velocity continually update

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#619]
@Carifio24 reported this. Can you please provide some more notes on which branch you were on and what you were doing? We so far haven't been able to reproduce this.

**Comment by Carifio24** [comment]
I'm not seeing this anymore, and I'm thinking that it perhaps it was related to #618 and https://github.com/cosmicds/cosmicds/pull/337 via some bad state loading. I'll reopen in this happens again.
