### ISSUE TITLE
Should zoom reset between galaxy measurements?

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#646]
This is on #629. (I haven't checked if this also happens on main, but we are about to merge that PR anyway). I just noticed that if you zoom in while making a spectrum measurement, when you choose a new galaxy, the zoom range stays zoomed in. (See video).

https://github.com/user-attachments/assets/c5473cd0-f2b6-4499-ab8e-910dbd9da4bc

It's convenient that the zoom range does not reset between galaxies, but it could be problematic if two galaxies are far enough apart in redshift that the H-alpha of the 2nd galaxy does not appear in the zoomed in range, so I think we probably need to always reset the zoom between galaxy measurements.

@johnarban, what do you think?

**Comment by johnarban** [comment]
I have noticed it too. In the solara version it has always stayed zoomed. I think the zoom should reset when the galaxy changes, not between measurements (someone may click more than once thinking about where to measure and would not expect that to cause a zoom out).  I put that in #651
