### ISSUE TITLE
Track down discrepancy btw dot plot velocities & observed wavelengths in spectrum viewer when zoomed in

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#649]
Take, for example, the seed measurement from student 3440:
- 'velocity_value': 12109 km/s
- 'obs_wave_value': 6830 A

The observed wavelength line is not appearing in the right place:

<img width="1165" alt="Screenshot 2024-10-09 at 6 48 11 PM" src="https://github.com/user-attachments/assets/874d53ce-b54f-48da-ac53-cab473595324">

**Comment by johnarban** [comment]
This issue seems to be resolved on #657
