### ISSUE TITLE
Updating the position of the second measurement is no longer work

### ISSUE THREAD

**Issue by johnarban** [cosmicds/hubbleds#652]
I only just noticed this on #651, but it seems to be present on main. This was definitely working before. It runs `add_example_measurements_to_glue()` when the measurement changes as it is supposed to (`update_second_example_measurement()` is poorly named and not responsible for this, it is only used to initialize the second measurement). 

So it runs, and the glue data set is updated, but the dotplot does not update. It does not seem to be an issue with @Carifio24 changes in #647, as it doesn't work on commits prior to it. I am unsure what is causing this.

**Comment by johnarban** [comment]
Just a note to confirm that this is still broken in #657. The background glue object is being updated, but the dotplot does not show that.

**Comment by Carifio24** [comment]
Sorry if I'm forgetting something obvious, but what is it that isn't updating? The dotplot seems to update for me when I change between the markers where we switch from first to second measurement.

https://github.com/user-attachments/assets/c7a86050-47c7-45a4-aca4-0e4351907987

**Comment by johnarban** [comment]
Ah, no. So the issues that on `rem_vel1` clicking on the spectrum should make a new measurement, which should be reflected by the green dot on the dotplot. Instead the dot does not move. But when we advance to `dot_seq14` it suddenly shows up in the new location, if we got back to `rem_vel1` the dotplot still shows the old position. 

https://github.com/user-attachments/assets/07a6da1a-2fe2-48f3-9d77-540d47bec49a
