### ISSUE TITLE
Set up analytics tracking on hubbleds

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#654]
We want this on the demo app where data are not written to the db, but we might as well track usage of all the stories & educator dashboard, etc.

- make a component like what we do with mathjax & plotly
- look on solara github or discourse to see if someone has already solved this.
- is there a head component where we can add stuff? (yes, but all it supports is page title.) https://solara.dev/documentation/components/page/head
- custom.js asset file.

**Comment by Carifio24** [comment]
@patudom Do we have a Google Analytics ID for `app.cosmicds.cfa.harvard.edu`?
