### ISSUE TITLE
Remaining Stage 1 issues

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#656]
Somethings I noticed that should be fixed in a later PR (that exist on main as well) are
 1) that the velocity for the real galaxies does not update if the student changes their measurement, they would have to press the fill velocities button. We either want to prevent changes, or automatically update them.
2) Selecting the galaxy does not seem to put it in the WWT view

_Originally posted by @johnarban in https://github.com/cosmicds/hubbleds/pull/653#pullrequestreview-2363233183_

**Comment by patudom** [comment]
Thanks, @johnarban! I'm not sure what's going on with item 2 because that used to work until very recently, so we must have broken it in one of our later PRs. I should have checked before I merged in #653, but was item 2 definitely broken on main before I merged 653?

**Comment by johnarban** [comment]
I feel like it wasn't broken before, and that it worked, but that part of the code I don't think has been touched in a while

**Comment by patudom** [comment]
Ok, if it wasn't broken on main before, I might have an idea of what I did in #653 that broke it. I will try to fix it in a new branch. If I don't succeed, I will reach out. Thanks!
