### ISSUE TITLE
Add numbers to left navigation menu like in voila

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#666]
At the ends of stages, we say "proceed to stage `N`". This may be a bit confusing if we don't number the stages the way we did in voila. Can we change those box icons to numbers?

This version:
<img width="695" alt="Screenshot 2024-10-18 at 11 32 46 AM" src="https://github.com/user-attachments/assets/078580b7-4ef4-46ef-8b01-dd0a293c6af7">

Voila version:
<img width="270" alt="Screenshot 2024-10-18 at 11 32 55 AM" src="https://github.com/user-attachments/assets/25901c44-dece-46d2-85f9-368d8b999f43">

**Comment by Carifio24** [comment]
@patudom What about something like this? AFAICT these are the only numeric circle MDI icons (the previous numbers came from the v-stepper component, which we aren't using anymore)

![Screenshot from 2024-10-18 11-54-03](https://github.com/user-attachments/assets/fdef19cc-44ca-4b51-86a1-13224cdafb02)

**Comment by patudom** [comment]
That's great - thank you!

**Comment by patudom** [comment]
Can we merge this to both the demo branch and main?

**Comment by Carifio24** [comment]
Oops, sorry, deleted the image by mistake. Here it is again:
![Screenshot from 2024-10-18 11-54-03](https://github.com/user-attachments/assets/25ed55ab-1e82-48c3-b86c-040b5c105824)

**Comment by Carifio24** [comment]
@patudom This is a cosmicds-level change so both versions will pick this up.

**Comment by Carifio24** [comment]
Also, FWIW I was able to recreate the menu using the v-stepper component that we have previously used in voila, but the routing behavior was not as nice (it seemed to reload the app on each route). Something about the navigation drawer with `nav=True` must work better with the Solara routing.

**Comment by patudom** [comment]
> @patudom This is a cosmicds-level change so both versions will pick this up.

Are we not using https://github.com/cosmicds/cosmicds/tree/public-demo for the demo version?
