### ISSUE TITLE
Make sure logger messages make sense

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#671]
Regarding the demo-branch:

some of the logger messages in the state (like e.g. https://github.com/cosmicds/hubbleds/blob/main/src/hubbleds/pages/01-spectra-%26-velocity/__init__.py#L98) are a bit confusing - the DB writing is correctly skipped and the logger message inside the API handler logs this, but you then see a "Wrote to the database" message.

_Originally posted by @Carifio24 in https://github.com/cosmicds/hubbleds/issues/665#issuecomment-2423297133_

**Comment by johnarban** [comment]
Yeah, that is because writing is prevented in the `put_stage_state` call, but there is no way for `_write_component_state` to know that, so it just runs the lines and prints the messages. We could probably just remove this message

**Comment by johnarban** [comment]
This issue should be fixed in https://github.com/johnarban/hubbleds/commit/1aaf29a6ac0f6eb4b686c833af014d098f66078d on PR #675
