### ISSUE TITLE
Stage 5 classes slider viewer has a blank class

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#682]
(I'm seeing this on the demo branch, but I'm guessing it'll be on main too because I don't see why the demo would be pulling different data).

<img width="1228" alt="Screenshot 2024-10-29 at 10 30 12 PM" src="https://github.com/user-attachments/assets/e595399d-e21d-49dc-8743-298c731967a1">

**Comment by Carifio24** [comment]
Just for future reference, we think this went away because of some updates to backend data processing.
