### ISSUE TITLE
Set up test viewer that points to SDSS DR12 to test performance relative to DR6

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#691]

**Comment by Carifio24** [comment]
Just to have a record of it:

* There's a viewer that gets its SDSS tiles directly from the staging instance (bypassing the CDN) [here](https://web.wwtassets.org/research/latest/?script=eyJldmVudCI6ImNlbnRlcl9vbl9jb29yZGluYXRlcyIsInJhIjoxNzguMzEyMzg4NDQwODQ5NiwiZGVjIjozOC4wNDg3NzIzNDE3NjkyOSwiZm92IjozMC4zMjM3MDYxODY1MzQzNzcsInJvbGwiOjAsImluc3RhbnQiOnRydWV9%2CeyJldmVudCI6InNldF9iYWNrZ3JvdW5kX2J5X25hbWUiLCJuYW1lIjoiU0RTUyAxMiBUZXN0In0%3D%2CeyJldmVudCI6ImxvYWRfaW1hZ2VfY29sbGVjdGlvbiIsInVybCI6Imh0dHBzOi8vcHJvamVjdHMuY29zbWljZHMuY2ZhLmhhcnZhcmQuZWR1L2Nkcy13ZWJzaXRlL3d3dC1jb250ZW50L1NEU1MxMlRlc3Qud3RtbCIsImxvYWRDaGlsZEZvbGRlcnMiOnRydWV9#)

* And, for comparison, a similar viewer that gets its SDSS tiles directly from the production instance (again, bypassing the CDN) [here](https://web.wwtassets.org/research/latest/?script=eyJldmVudCI6ImNlbnRlcl9vbl9jb29yZGluYXRlcyIsInJhIjoxOTAuMDU3NDk5NTM1MTM4MDUsImRlYyI6MjIuNzQ5MjkxNDI5OTAzNDc2LCJmb3YiOjUuMzQzNjU0OTExNTUwNjQ4LCJyb2xsIjowLCJpbnN0YW50Ijp0cnVlfQ%3D%3D%2CeyJldmVudCI6InNldF9iYWNrZ3JvdW5kX2J5X25hbWUiLCJuYW1lIjoiU0RTUyAxMiBUZXN0In0%3D%2CeyJldmVudCI6ImxvYWRfaW1hZ2VfY29sbGVjdGlvbiIsInVybCI6Imh0dHBzOi8vcHJvamVjdHMuY29zbWljZHMuY2ZhLmhhcnZhcmQuZWR1L2Nkcy13ZWJzaXRlL3d3dC1jb250ZW50L1NEU1MxMlByb2Qud3RtbCIsImxvYWRDaGlsZEZvbGRlcnMiOnRydWV9#)
