### ISSUE TITLE
Force hubble viewer backgrounds to always be white

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#703]
@johnarban gets a black background all his Stage 5 & 6 glue viewers, but my backgrounds are white. We need to make sure they are always white so the marker colors we choose contrast appropriately.

**Comment by Carifio24** [comment]
Just as a note, the Plotly viewers get their backgrounds from the user's glue config settings (ultimately, this comes from [here](https://github.com/glue-viz/glue-plotly/blob/main/glue_plotly/common/common.py#L46)). We can certainly make a way to directly override the config of the underlying Plotly figure if we want to, though.

**Comment by Carifio24** [comment]
I think https://github.com/cosmicds/cosmicds/pull/353 is the right solution for this. Rather than directly manipulating the Plotly figure config, I think it makes more sense for us to override any existing user glue settings, as this should apply to any other glue viewers that we use as well.
