### ISSUE TITLE
Stage 5: in the slider viewer with all the classes, the first class has an age but no data

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#708]
<img width="1423" alt="Screenshot 2024-12-12 at 6 02 56 PM" src="https://github.com/user-attachments/assets/c5a95d85-9ece-4fd4-8023-70b81a876503" />

**Comment by Carifio24** [comment]
This was an issue with the data returned from the server; it should be fixed with https://github.com/cosmicds/cds-api/pull/167. @patudom is this now fixed for you?

**Comment by patudom** [comment]
Yes, thank you, Jon!
